[package]
name = "arch"
version = "0.1.0"
authors = ["The Chromium OS Authors"]

[dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.4"
libc = ">=0.2.39"
utils = { path = "../utils" }

arch_gen = { path = "../arch_gen" }
vm-memory = { version = ">=0.2.0", features = ["backend-mmap"] }

[dev-dependencies]
utils = { path = "../utils" }
device_tree = ">=1.1.0"

[features]
hugetlb = []