[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"
dumbo = { path = "../dumbo" }
logger = { path = "../logger" }
vm-memory = { version = ">=0.2.0", features = ["backend-mmap"] }
utils = { path = "../utils" }
net_gen = { path = "../net_gen" }
polly = { path = "../polly" }
rate_limiter = { path = "../rate_limiter" }
snapshot = { path = "../snapshot" }
versionize = { path = "../versionize" }
versionize_derive = { path = "../versionize_derive" }
virtio_gen = { path = "../virtio_gen" }

vhost_rs = { git = "https://github.com/cloud-hypervisor/vhost", branch = "dragonball", package = "vhost", features = ["vhost-user-master"] }
