[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
kvm-bindings = { version = ">=0.2", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.4"
libc = ">=0.2.39"
serde = ">=1.0.27"
serde_derive = ">=1.0.27"
serde_json = ">=1.0.9"

arch = { path = "../arch" }
devices = { path = "../devices" }
dumbo = { path = "../dumbo" }
kernel = { path = "../kernel" }
logger = { path = "../logger" }
vm-memory = { version = ">=0.2.0", features = ["backend-mmap"] }
mmds = { path = "../mmds" }
utils = { path = "../utils"}
rate_limiter = { path = "../rate_limiter" }
seccomp = { path = "../seccomp" }
polly = { path = "../polly" }
snapshot = { path = "../snapshot"}

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpuid = { path = "../cpuid" }

[dev-dependencies]
vmm-sys-util = ">=0.4.0"


[features]
hugetlb = []