[package]
name = "firecracker"
version = "0.21.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
backtrace = {version = ">=0.3.35", features = ["libunwind", "libbacktrace", "std"], default-features = false}
libc = ">=0.2.39"
timerfd = ">=1.0"

api_server = { path = "../api_server" }
logger = { path = "../logger" }
mmds = { path = "../mmds" }
polly = { path = "../polly" }
seccomp = { path = "../seccomp" }
utils = { path = "../utils" }
vmm = { path = "../vmm" }

[features]
default = ["hugetlb"]
hugetlb = ["api_server/hugetlb"]